// <auto-generated />
namespace ReExamAppV2._3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tablesandrelationsadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tablesandrelationsadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201702251955558_tables and relations added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
